# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: JS Park
email: contact@jspk.site

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jspk.site" # the base hostname & protocol for your site, e.g. http://example.com

# jekyll-seo-tag plugin

description: >- # this means to ignore newlines until "baseurl:"
  Front-End Developer & Designer
tagline: "JS Park - Front-End Developer & Designer"
author: JS Park
twitter:
  card: summary
logo: 
social:
  name: JS Park
  links:
    - https://instagram.com/js___pk
    - https://www.linkedin.com/in/jspk/
    - https://github.com/js-pk
defaults: 
  - scope:
      path: ""
    values:
      image:
        path: "/assets/images/thumbnail.jpg"
        height: 1009
        width: 1200
        alt: "jspk site thumbnail"

github_username:  js-pk
instagram_username: js___pk
linkedin_username: jspk

google_analytics: "G-S2J8KED61T"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# defaults:
#   - scope:
#       path: "assets/images"
#     values:
#       image: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
